name: "nest-starter"

services:
  api:
    image: nest
    build:
      context: ../
      dockerfile: deployments/prod.Dockerfile
    container_name: nest
    ports:
      - 3000:3000
    restart: unless-stopped
