version: "3"
services:
  nest:
    build:
      context: .
      dockerfile: deployments/prod.Dockerfile
    image: nest
    container_name: nest
    ports:
      - 3000:3000
    restart: unless-stopped
